services:
  db:
    container_name: "db"
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=S#nQ^7qP@yH5
      - TZ=America/Lima
    volumes:
      - /data-bd:/var/lib/mysql
      - /usr/share/zoneinfo/America/Lima:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
      - "3306:3306"
    restart: always
    networks:
      mintec-networks:
        ipv4_address: 172.10.0.25
  adminer:
      container_name: "adminer"
      image: adminer
      restart: always
      networks:
        mintec-networks:
          ipv4_address: 172.10.0.24
  nginx-main:
    container_name: "nginx-main"
    build:
      context: ./nginx-router-balance
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      mintec-networks: 
        ipv4_address: 172.10.0.10
  api-delegada:
      build:
        context: ./php-composer
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
        - "5173:5173"
      restart: unless-stopped
      volumes:
        - /home/antonio/proyectos-trabajo/c3app/:/home/antonio/proyectos-trabajo/c3app/
      networks:
        mintec-networks:
          ipv4_address: 172.10.0.50
networks:
  mintec-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
